<?php

use Drupal\cp22_escp_article\Manager\ArticleNodeManager;
use Drupal\cp22_escp_article_list\Manager\ArticleListNodeManager;
use Drupal\node\NodeInterface;


/**
 * Implements hook_preprocess_HOOK().
 */
function cp22_escp_article_list_preprocess_node(&$variables) {

  /** @var NodeInterface $node */
  $node = $variables['node'];

  // If we are on the list page article
  if($node->bundle() == ArticleListNodeManager::NODE_TYPE && $variables['view_mode'] == "full") {
    $articleNodeManager = \Drupal::service(ArticleNodeManager::class);

    // We send a filter date form and recover the data
    $variables['sort_date_form'] = \Drupal::formBuilder()->getForm('Drupal\cp22_escp_global\Form\GlobalNodeSortForm');
    $date_sort = \Drupal::requestStack()->getCurrentRequest()->get('node_sort_changed_date_form');

    // We load all the articles
    $variables["#cache"]["tags"][] = 'node:article';
    $variables['all_articles'] = $articleNodeManager->getBuiltPublishedNodesArticleWithPagerAndLanguageByDate($date_sort);

    // the pager of 10 articles
    $variables['pager'] = [
      '#type' =>  'pager'
    ];

  }

}
