<?php

use Drupal\cp22_escp_article\Manager\ArticleNodeManager;
use Drupal\cp22_escp_socials\Manager\SocialsTermsManager;
use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function cp22_escp_article_preprocess_node(&$variables)
{
  /** @var NodeInterface $node */
  $node = $variables['node'];

  // If we are on the home page
  if ($node->bundle() == ArticleNodeManager::NODE_TYPE && $variables['view_mode'] == "full" ) {
    $socialManager = \Drupal::service(SocialsTermsManager::class);
    $articleManager = \Drupal::service(ArticleNodeManager::class);

    // The socials Terms to display on the picture
    $variables['social_terms'] = $socialManager->getbuiltPublishedTermsListByWeight();


    //The cloud of terms
    $variables['terms_cloud'] = $articleManager->getTheCloudOfTermsThemes();

    $variables["#cache"]["tags"][] = 'node:article';
    // Send the link to the previous and next article. If no possibilities, does not appear on the twig
    $variables['previous_article'] = $articleManager->getThePreviousArticleLinkBuiltDependsOnTheCurrentPageArticleNode();
    $variables['next_article'] = $articleManager->getTheNextArticleLinkBuiltDependsOnTheCurrentPageArticleNode();
  }


}
