<?php

use Drupal\cp22_escp_article\Manager\ArticleNodeManager;
use Drupal\cp22_escp_article_list\Manager\ArticleListNodeManager;
use Drupal\cp22_escp_author\Manager\AuthorListNodeManager;
use Drupal\cp22_escp_author\Manager\AuthorNodeManager;
use Drupal\node\NodeInterface;


/**
 * Implements hook_preprocess_HOOK().
 */
function cp22_escp_author_preprocess_node(&$variables)
{
  /** @var NodeInterface $node */
  $node = $variables['node'];

  // If we are on the page of an author
  if ($node->bundle() == AuthorNodeManager::PAGE_BUNDLE && $variables['view_mode'] == "full" ) {
    $authorNodeManager = \Drupal::service(AuthorNodeManager::class);

    // We load all the articles of this author
    $variables['all_articles_from_author']= $authorNodeManager->getNodesArticleSortDescWithPagerAndLanguageByAuthor();
  }

}
